name: Publish Over-the-Air Update PR
on:
  pull_request:
    paths:
      - 'src/**'
      - 'App.tsx'
      - '.github/workflows/publish-ota-update-pr.yml'
      - 'scripts/ota-PR.sh'
      - 'scripts/getRandomVersion.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish-ota-update:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.SIGNING_REPO_PAT }}

      - name: ğŸ–¥ Setup Bun
        uses: ./.github/actions/setup-bun

      - name: ğŸ‘©â€ğŸ’» Configure Git
        run: |
          git config --global user.email "violet@cosmonautical.cloud"
          git config --global user.name "anultravioletaurora"

      - name: ğŸ¤– Publish Update
        run: bun run sendOTA:PR ${{ github.event.pull_request.number }}
        env:
          SIGNING_REPO_PAT: ${{ secrets.SIGNING_REPO_PAT }}
